Add text editing functionality to EditModeManager
- Introduced methods to make text elements editable, allowing users to modify content directly.
- Implemented event handling for saving or discarding changes on blur or key events.
- Enhanced mouse event handling to differentiate between text and non-text elements for editing.
- Updated state management to track currently editing elements and their original content.

- Work in progess. We havesome error:

```
content-2bc5c64b.js:125 Error while finishing edit: TypeError: Cannot read properties of null (reading 'setAttribute')
    at r (content-2bc5c64b.js:125:2199)
    at HTMLHeadingElement.l (content-2bc5c64b.js:125:2925)
r	@	content-2bc5c64b.js:125
l	@	content-2bc5c64b.js:125
```